version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "typescript-eslint"
          - "@typescript-eslint/*"
      next:
        patterns:
          - "next"
          - "@next/*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
